import {test,expect} from '@playwright/test';
test('local model test discovers models, sends only explicit context, and falls back on failure',async({page})=>{
 let requests=0;let failed=false;
 await page.route('http://192.168.1.23:1234/v1/**',async route=>{
  const chat=route.request().url().endsWith('/chat/completions');
  if(chat){requests++;expect(route.request().postDataJSON().model).toBe('test-local-model');}
  if(failed)return route.fulfill({status:503,body:'unavailable'});
  return route.fulfill({contentType:'application/json',body:JSON.stringify(chat?{choices:[{message:{content:'Model response from the test server.'}}]}:{data:[{id:'test-local-model'}]})});
 });
 await page.goto('/');await page.getByRole('button',{name:'Settings and backup'}).click();await page.getByRole('switch',{name:'Labs',exact:true}).click();await page.getByLabel('Local OpenAI-compatible endpoint').fill('http://192.168.1.23:1234/v1');await page.getByRole('button',{name:'Test connection',exact:true}).click();await expect(page.locator('.model-status')).toContainText('Connected');await expect(page.getByLabel('Model',{exact:true})).toHaveValue('test-local-model');expect(requests).toBe(0);
 await page.reload();await page.getByRole('button',{name:'Settings and backup'}).click();await expect(page.getByLabel('Local OpenAI-compatible endpoint')).toHaveValue('http://192.168.1.23:1234/v1');await expect(page.locator('.model-status')).toContainText('Not tested');
 await page.locator('.mobile-nav').getByRole('button',{name:'Assistant'}).click();await page.getByRole('button',{name:'What matters today?',exact:true}).click();expect(requests).toBe(0);await page.getByRole('checkbox',{name:/Use my local model/}).check();await page.getByLabel('Assistant question').fill('Summarize today');await page.getByRole('button',{name:'Send question'}).click();await expect(page.getByRole('log')).toContainText('Model response from the test server.');expect(requests).toBe(1);
 failed=true;await page.getByLabel('Assistant question').fill('What matters today?');await page.getByRole('button',{name:'Send question'}).click();await expect(page.getByRole('log')).toContainText('HTTP 503');await expect(page.getByRole('log')).toContainText('Nothing pressing');
});
test('editing cannot silently discard changes and moving a note updates search and survives reload',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Capture something'}).click();await page.getByLabel('Capture text').fill('A useful note');await page.getByRole('button',{name:'note',exact:true}).click();await page.getByRole('button',{name:'Save capture'}).click();await page.locator('.mobile-nav').getByRole('button',{name:'Search'}).click();await page.getByRole('button',{name:'Open A useful note',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('A better note');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Discard changes'})).toBeVisible();await page.getByRole('button',{name:'Keep editing'}).click();await page.getByLabel('Space',{exact:true}).selectOption('ejj');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.locator('.mobile-nav').getByRole('button',{name:'Search'}).click();await page.getByRole('button',{name:'EJJ Digital',exact:true}).last().click();await expect(page.getByRole('button',{name:'Open A better note'})).toBeVisible();
});
test('empty focus command is absent and filtered leads can return to the pipeline',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Today',exact:true})).toBeVisible();await page.keyboard.press('Control+k');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Start focus',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Close dialog'}).click();await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/EJJ Digital/}).click();await page.getByRole('button',{name:'Interested',exact:true}).click();await expect(page.getByText('No leads match this view.')).toBeVisible();await page.locator('.empty').getByRole('button',{name:'All leads',exact:true}).click();await expect(page.getByText('Your next relationship begins here.')).toBeVisible();
});
test('recording playback, slowdown and A/B loop operate on the uploaded audio',async({page})=>{
 const rate=8000,seconds=3,samples=rate*seconds,wav=Buffer.alloc(44+samples*2);wav.write('RIFF');wav.writeUInt32LE(36+samples*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(samples*2,40);for(let i=0;i<samples;i++)wav.writeInt16LE(Math.round(Math.sin(i/rate*Math.PI*440*2)*2000),44+i*2);
 await page.goto('/');await page.getByRole('button',{name:'Capture something'}).click();await page.getByLabel('Capture text').fill('Practice recording note');await page.getByRole('button',{name:'note',exact:true}).click();await page.getByRole('button',{name:'Save capture'}).click();await page.locator('.mobile-nav').getByRole('button',{name:'Search'}).click();await page.getByRole('button',{name:'Open Practice recording note'}).click();await page.locator('.file-button input').setInputFiles({name:'practice.wav',mimeType:'audio/wav',buffer:wav});await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('button',{name:'Open Practice recording note'}).click();await page.getByRole('button',{name:'Practise',exact:true}).click();await expect.poll(()=>page.locator('audio').evaluate((a:HTMLAudioElement)=>a.readyState)).toBeGreaterThan(2);await page.getByRole('button',{name:'0.75×',exact:true}).click();expect(await page.locator('audio').evaluate((a:HTMLAudioElement)=>a.playbackRate)).toBe(.75);
 await page.locator('audio').evaluate((a:HTMLAudioElement)=>{a.currentTime=.4});await page.getByRole('button',{name:/^A:/}).click();await page.locator('audio').evaluate((a:HTMLAudioElement)=>{a.currentTime=1});await page.getByRole('button',{name:/^B:/}).click();await page.getByRole('button',{name:'Loop',exact:true}).click();expect(await page.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeCloseTo(.4,1);await page.getByRole('button',{name:'Play recording',exact:true}).click();await expect.poll(()=>page.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(.5);await page.waitForTimeout(1500);expect(await page.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeLessThan(1.3);await page.getByRole('button',{name:'Close dialog'}).click();await expect(page.locator('audio')).toHaveCount(0);
});
