import {test,expect} from '@playwright/test';
test('chapter has its own editor, durable typed draft, and explicit canon confirmation',async({page})=>{
 await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/Moshia/}).click();
 await page.getByRole('button',{name:'Add chapter',exact:true}).first().click();const sheet=page.getByRole('dialog',{name:'Add chapter'});await expect(sheet).toBeVisible();await expect(sheet.getByText('Capture',{exact:true})).toHaveCount(0);
 await sheet.getByLabel('Chapter title',{exact:true}).fill('Chapter: a literal title');await sheet.getByLabel('Point of view',{exact:true}).fill('A narrator');await sheet.getByLabel('Purpose',{exact:true}).fill('Resolve the test thread');await sheet.getByRole('button',{name:'Close dialog'}).click();await page.reload();
 await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/Moshia/}).click();await page.getByRole('button',{name:'Add chapter',exact:true}).first().click();await expect(sheet.getByLabel('Chapter title',{exact:true})).toHaveValue('Chapter: a literal title');await expect(sheet.getByLabel('Point of view',{exact:true})).toHaveValue('A narrator');
 await sheet.getByLabel('Story state',{exact:true}).selectOption('CANON');await sheet.getByRole('button',{name:'Add chapter',exact:true}).click();await expect(sheet.getByText('Add this to canon?',{exact:true})).toBeVisible();await sheet.getByRole('button',{name:'Add to canon',exact:true}).click();await expect(sheet).toHaveCount(0);
 await page.locator('.mobile-nav').getByRole('button',{name:'Search'}).click();await page.getByRole('button',{name:'Open Chapter: a literal title',exact:true}).click();await expect(page.getByLabel('POV',{exact:true})).toHaveValue('A narrator');await expect(page.getByRole('combobox',{name:'State',exact:true})).toHaveValue('CANON');await page.getByRole('button',{name:'Close dialog'}).click();
 await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await expect(page.getByRole('dialog',{name:'Capture',exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Capture text'})).toHaveValue('');
});
test('Moshia plot threads, locations, research and ideas have relevant creation fields and surfaces',async({page})=>{
 await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/Moshia/}).click();
 for(const item of [{tab:'Plot threads',noun:'plot thread',label:'Thread title',field:'Setup',value:'A quiet setup'},{tab:'Locations',noun:'location',label:'Location name',field:'Description',value:'A place with history'},{tab:'Research',noun:'research',label:'Research title',field:'Source',value:'A local source'},{tab:'Ideas',noun:'idea',label:'Idea title',field:'The idea',value:'A possibility, not a task'}]){
  await page.getByRole('button',{name:item.tab,exact:false}).first().click();await page.getByRole('button',{name:'Add '+item.noun,exact:true}).first().click();const sheet=page.getByRole('dialog',{name:'Add '+item.noun});await expect(sheet).toBeVisible();await sheet.getByLabel(item.label,{exact:true}).fill('Test '+item.noun);await sheet.getByLabel(item.field,{exact:true}).fill(item.value);await sheet.getByRole('button',{name:'Add '+item.noun,exact:true}).click();await expect(page.getByRole('button',{name:'Open Test '+item.noun,exact:true})).toBeVisible();await expect(page.locator('.story-collection')).toContainText(item.value);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }
});
test('dock lens follows intermediate finger positions and changes screens only on release',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Today',exact:true})).toBeVisible();const nav=page.locator('.mobile-nav');const bounds=(await nav.boundingBox())!;const step=(bounds.width-14)/5,start=bounds.x+7+step/2,y=bounds.y+bounds.height/2;
 await page.mouse.move(start,y);await page.mouse.down();await page.mouse.move(start+step*.35,y,{steps:10});await page.evaluate(()=>new Promise(requestAnimationFrame));const offset=await nav.locator('.dock-selection').evaluate(e=>new DOMMatrixReadOnly(getComputedStyle(e).transform).m41);expect(offset).toBeGreaterThan(step*.25);expect(offset).toBeLessThan(step*.45);await expect(page.getByRole('heading',{name:'Today',exact:true})).toBeVisible();
 await page.mouse.move(start+step,y,{steps:20});await expect(page.getByRole('heading',{name:'Today',exact:true})).toBeVisible();await page.mouse.up();await expect(page.getByRole('heading',{name:'Spaces',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);
});
