import {test,expect} from '@playwright/test';
test('workspace assistant shares scoped records and reviews creation before saving',async({page})=>{
 const credential='a'.repeat(64);let request:any;
 await page.route('**/api/assistant',async route=>{if(route.request().method()==='GET')return route.fulfill({json:{configured:true}});request=route.request().postDataJSON();await route.fulfill({json:{text:'Here is a possible chapter to review.',recordIds:[],actions:[{type:'create',title:'Add a possible chapter',fields:{space:'moshia',kind:'chapter',title:'Reviewed chapter',body:'A planning note',status:'POSSIBLE',data:{POV:'Narrator'}}}]}})});
 await page.goto('/#assistant='+credential);await page.locator('.mobile-nav').getByRole('button',{name:'Assistant',exact:true}).click();await expect(page.locator('.assistant-connection')).toHaveText('Gemini');await page.getByRole('button',{name:'Moshia',exact:true}).click();await page.getByRole('textbox',{name:'Assistant question'}).fill('Add a chapter');await page.getByRole('button',{name:'Send question'}).click();await expect(page.getByText('Here is a possible chapter to review.')).toBeVisible();expect(request.records.every((r:any)=>r.space==='moshia')).toBe(true);
 await page.getByRole('button',{name:'Review: Add a possible chapter'}).click();await page.getByRole('button',{name:'Review new item'}).click();const dialog=page.getByRole('dialog',{name:'Add chapter'});await expect(dialog.getByLabel('Chapter title',{exact:true})).toHaveValue('Reviewed chapter');await expect(dialog.getByLabel('Point of view',{exact:true})).toHaveValue('Narrator');await dialog.getByRole('button',{name:'Add chapter',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.locator('.mobile-nav').getByRole('button',{name:'Spaces',exact:true}).click();await page.locator('.spaces-large').getByRole('button',{name:/Moshia/}).click();await expect(page.getByRole('button',{name:'Open Chapter 1: Reviewed chapter'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('private workspace briefs load once without replacing edited data',async({page})=>{
 const item={id:'ediz-context-test-personal',space:'personal',kind:'note',title:'Owner context',body:'Confirmed owner facts',status:'active',created:new Date().toISOString(),updated:new Date().toISOString(),data:{contextType:'workspace-brief'}};
 await page.route('**/api/assistant?context=1',route=>route.fulfill({json:{items:[item]}}));await page.route('**/api/assistant',route=>route.fulfill({json:{configured:true}}));await page.goto('/#assistant='+'a'.repeat(64));await page.locator('.mobile-nav').getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:'Open Owner context',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'Notes',exact:true}).fill('My corrected facts');await dialog.getByRole('button',{name:'Save changes'}).click();await expect(dialog).toHaveCount(0);await page.reload();await page.locator('.mobile-nav').getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:'Open Owner context',exact:true}).click();await expect(page.getByRole('dialog').getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('My corrected facts');
});
