import {test,expect} from '@playwright/test';
test('capture drafts survive dismissal and reload; save clears the draft',async({page})=>{await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await page.getByRole('textbox',{name:'Capture text'}).fill('A thought I am not ready to save');await page.getByRole('button',{name:'idea',exact:true}).click();await page.getByRole('button',{name:'Close dialog'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await expect(page.getByRole('textbox',{name:'Capture text'})).toHaveValue('A thought I am not ready to save');await expect(page.getByRole('button',{name:'idea',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Save capture'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await expect(page.getByRole('textbox',{name:'Capture text'})).toHaveValue('');});
test('home-screen instructions, accessible switch, app icon assets and short keyboard viewport',async({page,context})=>{await page.goto('/');await page.getByRole('button',{name:'Settings and backup'}).click();await page.getByRole('button',{name:/Ediz OS on your Home Screen/}).click();await expect(page.getByRole('dialog')).toContainText('Add to Home Screen');await expect(page.getByRole('dialog')).toContainText('Open as Web App');await page.getByRole('button',{name:'Close dialog'}).click();const labs=page.getByRole('switch',{name:'Labs',exact:true});await expect(labs).toHaveAttribute('aria-checked','false');await labs.focus();await page.keyboard.press('Space');await expect(labs).toHaveAttribute('aria-checked','true');await page.reload();await page.getByRole('button',{name:'Settings and backup'}).click();await expect(page.getByRole('switch',{name:'Labs',exact:true})).toHaveAttribute('aria-checked','true');await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.waitForTimeout(500);await context.setOffline(true);for(const src of ['/icon-180.png','/icon-192.png','/icon-512.png']){expect(await page.evaluate(async url=>(await fetch(url)).ok,src)).toBe(true)}await context.setOffline(false);await page.setViewportSize({width:402,height:470});await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await page.getByRole('textbox',{name:'Capture text'}).fill('Phone keyboard check');await page.getByRole('button',{name:'Save capture'}).scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:'Save capture'})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Save capture'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);});
test('slide across the glass dock and use a contextual assistant without a model',async({page})=>{
 await page.goto('/');const dock=page.locator('.mobile-nav');const today=await dock.getByRole('button',{name:'Today',exact:true}).boundingBox();const spaces=await dock.getByRole('button',{name:'Spaces',exact:true}).boundingBox();await page.mouse.move(today!.x+today!.width/2,today!.y+today!.height/2);await page.mouse.down();await page.mouse.move(spaces!.x+spaces!.width/2,spaces!.y+spaces!.height/2,{steps:12});await page.mouse.up();await expect(page.getByRole('heading',{name:'Spaces',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);
 await dock.getByRole('button',{name:'Capture'}).click();await page.getByRole('textbox',{name:'Capture text'}).fill('French homework tomorrow');await page.getByRole('button',{name:'Save capture'}).click();await dock.getByRole('button',{name:'Assistant'}).click();await page.getByRole('button',{name:'What matters today?'}).click();await expect(page.getByRole('log')).toContainText('Start with French homework');await page.getByRole('textbox',{name:'Assistant question'}).fill('Why that?');await page.getByRole('button',{name:'Send question'}).click();await expect(page.getByRole('log')).toContainText('French homework tomorrow:');await page.getByRole('textbox',{name:'Assistant question'}).fill('Remind me call Studio 41 tomorrow at 16');await page.getByRole('button',{name:'Send question'}).click();await page.getByRole('button',{name:'Review reminder'}).click();await expect(page.getByRole('textbox',{name:'Capture text'})).toHaveValue('call Studio 41 tomorrow at 16');await page.getByRole('button',{name:'Close dialog'}).click();
});
test('focus begins gently, pauses, resumes, and completes the selected work',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Capture something'}).click();await page.getByRole('textbox',{name:'Capture text'}).fill('Finish my work');await page.getByRole('button',{name:'Save capture'}).click();await page.getByRole('button',{name:'Focus',exact:true}).click();await expect(page.getByRole('button',{name:'Complete task'})).toHaveCount(0);await page.getByRole('button',{name:'Begin',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Complete task',exact:true}).click();await expect(page.locator('.focus-screen')).toHaveCount(0);await expect(page.getByRole('button',{name:'Complete Finish my work'})).toHaveCount(0);
});
