import {test,expect} from '@playwright/test';
test('density and workspace focus apply immediately, persist together, and affect Today',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Capture something'}).click();await page.getByRole('textbox',{name:'Capture text'}).fill('Moshia task');await page.getByRole('button',{name:'Save capture'}).click();
 await page.locator('.entity-row').first().scrollIntoViewIfNeeded();const comfortable=(await page.locator('.entity-row').first().boundingBox())!.height;
 await page.getByRole('button',{name:'Settings and backup'}).click();await page.getByRole('button',{name:'Compact',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-density','compact');
 await page.getByRole('button',{name:'Balanced',exact:true}).click();await page.getByRole('dialog',{name:'Focus on a space'}).getByRole('button',{name:/Moshia/}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.focus-choice')).toContainText('Moshia');
 await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page.getByRole('region',{name:'Focused on Moshia'})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('data-focus','moshia');await expect(page.locator('.day-brand .e-mark i').nth(1)).toHaveCSS('background-color','rgb(227, 184, 110)');await page.locator('.entity-row').first().scrollIntoViewIfNeeded();expect((await page.locator('.entity-row').first().boundingBox())!.height).toBeLessThan(comfortable);
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-density','compact');await expect(page.getByRole('region',{name:'Focused on Moshia'})).toBeVisible();await page.getByRole('button',{name:'Change focus',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:/Balanced/}).click();await expect(page.getByRole('region',{name:'Focused on Moshia'})).toHaveCount(0);
});
test('metronome starts a running audio graph, schedules tempo-accurate clicks, and stops cleanly',async({page})=>{
 await page.addInitScript(()=>{const Audio=window.AudioContext;if(!Audio)return;const evidence={contexts:[] as AudioContext[],clicks:[] as number[],peaks:[] as number[]};(window as any).__audio=evidence;window.AudioContext=class extends Audio{constructor(...args:any[]){super(...args);evidence.contexts.push(this)}createOscillator(){const node=super.createOscillator(),start=node.start.bind(node);node.start=(at=0)=>{evidence.clicks.push(at);start(at)};return node}createGain(){const node=super.createGain(),original=node.gain.exponentialRampToValueAtTime.bind(node.gain);node.gain.exponentialRampToValueAtTime=(value,at)=>{evidence.peaks.push(value);return original(value,at)};return node}}});
 await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/CLEARANCE/}).click();await page.getByRole('button',{name:'Rehearsal mode'}).click();await page.getByRole('spinbutton',{name:'Metronome BPM'}).fill('120');await page.getByRole('button',{name:'Start metronome',exact:true}).click();await expect(page.getByRole('button',{name:'Stop metronome',exact:true})).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>(window as any).__audio.clicks.length)).toBeGreaterThan(3);const evidence=await page.evaluate(()=>{const audio=(window as any).__audio;return {state:audio.contexts[0].state,clicks:audio.clicks.slice(0,4),peak:Math.max(...audio.peaks)}});expect(evidence.state).toBe('running');expect(evidence.peak).toBeGreaterThan(.1);for(let i=1;i<evidence.clicks.length;i++)expect(evidence.clicks[i]-evidence.clicks[i-1]).toBeCloseTo(.5,2);
 await page.getByRole('spinbutton',{name:'Metronome BPM'}).fill('180');await page.getByRole('button',{name:'Increase tempo'}).click();await expect(page.getByRole('spinbutton',{name:'Metronome BPM'})).toHaveValue('181');await page.getByRole('button',{name:'Decrease tempo'}).click();await expect(page.getByRole('spinbutton',{name:'Metronome BPM'})).toHaveValue('180');const before=await page.evaluate(()=>(window as any).__audio.clicks.length);await expect.poll(()=>page.evaluate(()=>(window as any).__audio.clicks.length)).toBeGreaterThan(before+3);const changed=await page.evaluate(()=>(window as any).__audio.clicks.slice(-3));expect(changed[2]-changed[1]).toBeCloseTo(1/3,2);
 await page.getByRole('button',{name:'Stop metronome',exact:true}).click();await expect(page.getByRole('button',{name:'Start metronome',exact:true})).toBeVisible();const stopped=await page.evaluate(()=>(window as any).__audio.clicks.length);await page.waitForTimeout(650);expect(await page.evaluate(()=>(window as any).__audio.clicks.length)).toBe(stopped);expect(await page.evaluate(()=>(window as any).__audio.contexts[0].state)).toBe('closed');
});
test('rehearsal setlist selection applies song tempo and respects navigation boundaries',async({page})=>{
 await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:/CLEARANCE/}).click();
 for(const [name,bpm] of [['First rehearsal song','120'],['Second rehearsal song','144']]){await page.getByRole('button',{name:'Add song'}).first().click();await page.getByRole('textbox',{name:'Song title',exact:true}).fill(name);await page.getByRole('textbox',{name:'BPM',exact:true}).fill(bpm);await page.getByRole('dialog').getByRole('button',{name:'Add song',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
 await page.getByRole('button',{name:'Rehearsal mode'}).click();await page.getByRole('button',{name:'Select First rehearsal song',exact:true}).click();await expect(page.getByRole('spinbutton',{name:'Metronome BPM'})).toHaveValue('120');await expect(page.getByRole('button',{name:'Previous',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Next song',exact:true}).click();await expect(page.getByRole('spinbutton',{name:'Metronome BPM'})).toHaveValue('144');await expect(page.getByRole('button',{name:'Next song',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Previous',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Start metronome'})).toBeInViewport();
});
test('workspace focus replaces Today with its own surface and persists after reload',async({page})=>{
 await page.goto('/');
 for(const title of ['Personal task first','EJJ follow up second','School homework today']){await page.locator('.mobile-nav').getByRole('button',{name:'Capture'}).click();await page.getByLabel('Capture text').fill(title);await page.getByRole('button',{name:'Save capture'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
 await page.getByRole('button',{name:'Focus on EJJ Digital',exact:true}).click();await expect(page.getByRole('region',{name:'Focused on EJJ Digital'})).toBeVisible();await expect(page.locator('.workspace-choice')).toHaveCount(0);await expect(page.locator('.next-move .row-main')).toHaveCount(1);await expect(page.locator('.next-move .row-main')).toContainText('EJJ follow up second');await expect(page.locator('.today-v2').getByText('School homework today',{exact:true})).toHaveCount(0);await expect(page.locator('.today-v2').getByText('Personal task first',{exact:true})).toHaveCount(0);await expect(page.locator('main')).toHaveAttribute('data-saving-preferences','false');await page.reload();await expect(page.getByRole('region',{name:'Focused on EJJ Digital'})).toBeVisible();
 await page.getByRole('button',{name:'All spaces',exact:true}).click();await page.getByRole('button',{name:'Focus on Moshia',exact:true}).click();await expect(page.getByRole('region',{name:'Focused on Moshia'})).toBeVisible();await expect(page.getByRole('button',{name:'Start a chapter',exact:true})).toBeVisible();await page.getByRole('button',{name:'Start a chapter',exact:true}).click();await expect(page.getByRole('dialog',{name:'Add chapter'})).toBeVisible();await expect(page.getByLabel('Chapter title',{exact:true})).toBeVisible();
});

test('continuity desk separates established canon and opens the saved chapter',async({page})=>{
 await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Spaces'}).click();await page.locator('.spaces-large').getByRole('button',{name:'Moshia',exact:false}).first().click();
 await page.getByRole('button',{name:'Add chapter',exact:true}).first().click();await page.getByRole('textbox',{name:'Chapter title',exact:true}).fill('Continuity chapter');await page.getByRole('dialog').getByRole('button',{name:'Add chapter',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.locator('.story-desk summary').click();await expect(page.locator('.story-desk')).toContainText('1 chapters');await expect(page.locator('.story-desk')).toContainText('0 canon records');await page.locator('.story-desk').getByRole('button',{name:'Continuity chapter',exact:true}).click();await expect(page.getByRole('dialog').getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Continuity chapter');
});
