import {rank,search,parseCapture,spaces,type Entity,type Settings} from './core';
export interface AssistantAnswer {text:string;records?:Entity[];draft?:Partial<Entity>}
export function answerQuestion(question:string,items:Entity[],settings:Settings,previousIds:string[]=[],now=new Date()):AssistantAnswer{
 const q=question.toLowerCase().trim(),p=rank(items,now,settings.focus),previous=previousIds.map(id=>items.find(e=>e.id===id)).filter((e):e is Entity=>!!e);
 if(/^(remind me|capture|add a task)\b/.test(q)){const text=question.replace(/^(remind me|capture|add a task)\s*:?[\s]*/i,'');if(!text.trim())return {text:'What would you like to remember?'};return {text:'I’ve prepared a reminder. Review its space and date before saving it.',draft:parseCapture(text,now)}}
 if(/\b(why|reason)\b/.test(q)){const targets=previous.length?previous:p.slice(0,1).map(x=>x.entity);return {text:targets.length?targets.map(e=>`${e.title}: ${p.find(x=>x.entity.id===e.id)?.reasons.join(' ')||'This was part of our previous conversation. Its current state is '+e.status+'.'}`).join('\n\n'):'There isn’t a recommendation to explain yet. Bring in your work and I can explain each next step.',records:targets}}
 if(/\b(tomorrow|schedule|coming up)\b/.test(q)){const start=new Date(now);start.setHours(0,0,0,0);if(q.includes('tomorrow'))start.setDate(start.getDate()+1);const end=new Date(start);end.setDate(end.getDate()+(q.includes('tomorrow')?1:7));const due=items.filter(e=>e.due&&new Date(e.due)>=start&&new Date(e.due)<end&&!['done','archived','REJECTED'].includes(e.status)).sort((a,b)=>a.due!.localeCompare(b.due!));const duration=due.reduce((total,e)=>total+(e.duration||0),0);return {text:due.length?`${q.includes('tomorrow')?'Tomorrow':'Coming up'}: ${due.map(e=>e.title).join(', ')}.${duration?` The items with estimates add up to ${duration} minutes.`:''}${due.some(e=>!e.duration)?' Some items don’t have time estimates yet.':''}`:'There’s nothing scheduled '+(q.includes('tomorrow')?'for tomorrow.':'in the next seven days.'),records:due.slice(0,8)}}
 if(/\b(waiting|blocked|stale|neglected)\b/.test(q)){const list=items.filter(e=>q.includes('stale')||q.includes('neglected')? !['done','archived','REJECTED'].includes(e.status)&&now.getTime()-new Date(e.updated).getTime()>7*86400000:['waiting','blocked'].includes(e.status)||e.blocked);return {text:list.length?`${list.length} ${list.length===1?'item needs':'items need'} a check-in. ${list.map(e=>e.title).slice(0,5).join(', ')}. Open one to choose a realistic next step.`:'Nothing needs a check-in here right now.',records:list.slice(0,5)}}
 if(/\b(find|search|where|tell me about)\b/.test(q)){const term=question.replace(/^(find|search|where is|where|tell me about)\s*/i,'').replace(/[?]$/,'');const list=search(items,term);return {text:list.length?list.slice(0,5).map(e=>`${e.title} · ${e.status}${e.body?'\n'+e.body.slice(0,450):''}`).join('\n\n'):`I couldn’t find “${term}” in your saved work. Try a shorter name.`,records:list.slice(0,5)}}
 const space=spaces.find(s=>q.includes(s.name.toLowerCase())||q.includes(s.id));
 if(space){const list=items.filter(e=>e.space===space.id&&!['done','archived','REJECTED'].includes(e.status));const next=p.filter(x=>x.entity.space===space.id).slice(0,3);return {text:list.length?`${space.name} has ${list.length} active ${list.length===1?'item':'items'}. ${next.length?'Next: '+next.map(x=>x.entity.title).join(', ')+'.':'Your material is organized by type and state.'}${space.id==='moshia'?' POSSIBLE and PLANNED material remain separate from canon.':''}`:`${space.name} is ready for your own ${space.description.toLowerCase()}. Capture or import your material to start.`,records:next.length?next.map(x=>x.entity):list.slice(0,5)}}
 if(/\b(focus|next|today|matter|start|work on)\b/.test(q)){return {text:p.length?`Start with ${p[0].entity.title}. ${p[0].reasons.join(' ')}${p.length>1?' After that, '+p[1].entity.title+' is a sensible next step.':''}`:'Nothing pressing is saved yet. Capture a thought or import what you already have, and I’ll help you choose a next step.',records:p.slice(0,2).map(x=>x.entity)}}
 if(/\b(review|progress|done|completed)\b/.test(q)){const done=items.filter(e=>e.status==='done');return {text:done.length?`${done.length} completed ${done.length===1?'item':'items'} in your saved work. ${p.length?`${p[0].entity.title} is a good place to pick up next.`:'You have room to choose what comes next.'}`:'There are no completed items yet. You can ask me to choose a next step, review tomorrow or find something.',records:done.slice(-5)}}
 return {text:'I can help you choose what matters, explain a recommendation, plan tomorrow, find your material, check what’s waiting, or prepare a reminder. What would help right now?'};
}
