import {useState,useEffect,useRef} from 'react';
import {ArrowUp,Plus} from 'lucide-react';
import {answerQuestion,type AssistantAnswer} from './assistant';
import {LocalProvider} from './ai';
import {type Entity,type Settings} from './core';
interface Message extends AssistantAnswer{role:'user'|'assistant';id:string}
export function ConversationAssistant({items,settings,onCapture,onOpen}:{items:Entity[];settings:Settings;onCapture:(initial?:Partial<Entity>)=>void;onOpen:(entity:Entity)=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[local,setLocal]=useState(false);const last=useRef<HTMLDivElement>(null);
 useEffect(()=>{last.current?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},[messages]);
 async function ask(text:string){if(!text.trim()||busy)return;const previous=[...messages].reverse().find(m=>m.role==='assistant'&&m.records?.length)?.records?.map(e=>e.id)||[];setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:text.trim()}]);setQuestion('');let reply=answerQuestion(text,items,settings,previous);setBusy(true);
 if(local&&settings.labs&&settings.localEndpoint&&!reply.draft){try{const context=JSON.stringify({records:items.map(e=>({title:e.title,status:e.status,space:e.space,kind:e.kind,due:e.due})),conversation:messages.slice(-6).map(m=>({role:m.role,text:m.text}))});reply={...reply,text:await new LocalProvider(settings.localEndpoint,settings.localModel).suggest(text,context)}}catch(e){reply={...reply,text:reply.text+'\n\n'+(e instanceof Error?e.message:'Your local model is unavailable.')}}}
 setMessages(v=>[...v,{...reply,role:'assistant',id:crypto.randomUUID()}]);setBusy(false)}
 return <div className="assistant-page"><div className="page-heading"><h1>Assistant</h1><p>A second perspective on your own work.</p></div>{messages.length===0&&<><div className="assistant-intro"><h2>What would help, Ediz?</h2><p className="muted">Choose a next step, make room for tomorrow, or pick up a loose thread.</p></div><div className="assistant-context">{['What matters today?','What’s tomorrow like?','What’s waiting?'].map(q=><button className="quiet" key={q} onClick={()=>ask(q)}>{q}</button>)}</div></>}<div className="assistant-conversation" role="log" aria-live="polite">{messages.map(m=><div className={'conversation-message '+m.role} key={m.id}><p>{m.text}</p>{m.records&&<div className="assistant-linked">{m.records.map(r=>items.find(e=>e.id===r.id)).filter((e):e is Entity=>!!e).map(e=><button key={e.id} className="assistant-record" onClick={()=>onOpen(e)}><strong>{e.title}</strong><small>{e.status}</small></button>)}</div>}{m.draft&&<button className="quiet" onClick={()=>onCapture(m.draft)}><Plus size={17}/> Review reminder</button>}</div>)}{busy&&<p className="muted">A moment…</p>}<div ref={last}/></div><form className="assistant-composer" onSubmit={e=>{e.preventDefault();ask(question)}}><textarea aria-label="Assistant question" rows={2} placeholder="What’s on your mind?" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask(question)}}}/><button className="quiet" type="submit" aria-label="Send question" disabled={!question.trim()||busy}><ArrowUp size={21}/></button></form>{settings.labs&&settings.localEndpoint&&<label className="share-context"><input type="checkbox" checked={local} onChange={e=>setLocal(e.target.checked)}/> Use my local model and share record titles, states and this conversation.</label>}<p className="assistant-note">{local?'Local model requested; if unavailable, the reply includes your on-device result.':'Works on your device. Suggestions never change your records.'}</p></div>;
}
