export const spaces = [
 {id:'ejj',name:'EJJ Digital',description:'Leads & websites',mark:'E',color:'#405d7b'},
 {id:'band',name:'CLEARANCE 19',description:'Songs & rehearsal',mark:'19',color:'#a62d3d'},
 {id:'moshia',name:'Moshia',description:'Chapters & story world',mark:'M',color:'#635078'},
 {id:'school',name:'School',description:'Homework & timetable',mark:'S',color:'#9a7239'},
 {id:'personal',name:'Personal',description:'Tasks & everyday life',mark:'P',color:'#65517c'}
];
export type Kind='task'|'note'|'idea'|'event'|'lead'|'song'|'rehearsal'|'character'|'chapter'|'thread'|'location'|'organization'|'assignment'|'exam'|'subject'|'grade'|'website';
export interface Entity {id:string;space:string;kind:Kind;title:string;body:string;status:string;created:string;updated:string;due?:string;duration?:number;importance?:number;blocked?:boolean;data:Record<string,string>;}
export interface Activity {id:string;entityId:string;title:string;action:string;at:string;}
export interface Settings {density:'comfortable'|'compact';focus:string;theme:'light'|'dark'|'system';lastVisit:string;lastBackup?:string;localEndpoint?:string;labs:boolean;recentId?:string;}
export const defaults:Settings={density:'comfortable',focus:'all',theme:'dark',lastVisit:new Date().toISOString(),labs:false};
export const actionable=(e:Entity)=>['task','assignment','exam','lead'].includes(e.kind)&&!['done','Lost','Client','archived','waiting','blocked'].includes(e.status)&&!e.blocked;
export function priority(e:Entity, now=new Date(),focus='all') {let score=0;const reasons:string[]=[];if(!actionable(e))return {score:-1,reasons:['This item is not actionable.']};if(e.due){const days=(new Date(e.due).getTime()-now.getTime())/86400000;if(days<0){score+=65;reasons.push('Its planned date has passed; choose a realistic next step.');}else if(days<1){score+=60;reasons.push('It is due within the next 24 hours.');}else if(days<3){score+=40;reasons.push('Its deadline is approaching.');}else if(days<7){score+=20;reasons.push('It is coming up this week.');}}
score+=(e.importance||2)*8;if((e.importance||2)>=4)reasons.push('You marked this as important.');if(focus===e.space){score+=20;reasons.push('It matches your current focus.');}const age=(now.getTime()-new Date(e.updated).getTime())/86400000;score+=Math.min(15,Math.max(0,age));if(age>7)reasons.push('It has been quiet for more than a week.');if(e.kind==='lead'&&e.data.lastContact){const wait=(now.getTime()-new Date(e.data.lastContact).getTime())/86400000;if(wait>=4){score+=15;reasons.push('This relationship is ready for a follow-up.');}}if(e.duration&&e.duration<=25){score+=4;reasons.push('It fits into a short session.');}if(!reasons.length)reasons.push('An active next step in your system.');return {score,reasons};}
export function rank(items:Entity[],now=new Date(),focus='all'){return items.map(entity=>({entity,...priority(entity,now,focus)})).filter(x=>x.score>=0).sort((a,b)=>b.score-a.score||a.entity.created.localeCompare(b.entity.created));}
export function parseCapture(text:string,now=new Date()):Partial<Entity>{let space='personal';if(/studio|client|website|ejj|lead/i.test(text))space='ejj';if(/rehearsal|guitar|band|cable|song/i.test(text))space='band';if(/moshia|chapter|nathaniel|canon/i.test(text))space='moshia';if(/homework|french|school|exam|english|math/i.test(text))space='school';const kind:Kind=/\bidea\b/i.test(text)?'idea':/\bnote\b/i.test(text)?'note':/homework/i.test(text)?'assignment':'task';let due: string|undefined;const day=new Date(now);day.setHours(12,0,0,0);if(/tomorrow/i.test(text)){day.setDate(day.getDate()+1);due=day.toISOString();}else if(/\btoday\b/i.test(text)){due=day.toISOString();}else{const names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];const found=names.findIndex(n=>new RegExp('\\b'+n+'\\b','i').test(text));if(found>=0){day.setDate(day.getDate()+((found-day.getDay()+7)%7||7));due=day.toISOString();}const iso=text.match(/\b\d{4}-\d{2}-\d{2}\b/);if(iso&&!Number.isNaN(Date.parse(iso[0])))due=new Date(iso[0]+'T12:00:00').toISOString();}const time=text.match(/\b(?:at|@)\s*(\d{1,2})(?::(\d{2}))?\b/i);if(time&&Number(time[1])<24&&Number(time[2]||0)<60){const d=due?new Date(due):day;d.setHours(Number(time[1]),Number(time[2]||0));due=d.toISOString();}return {space,kind,title:text.trim().split('\n')[0].slice(0,200),body:text.trim().includes('\n')?text.trim().split('\n').slice(1).join('\n'):'',due,status:kind==='idea'?'new':'active'};}
export function makeEntity(input:Partial<Entity>):Entity{const now=new Date().toISOString();return {id:crypto.randomUUID(),space:'personal',kind:'task',title:'',body:'',status:'active',created:now,updated:now,importance:2,data:{},...input};}
export function search(items:Entity[],q:string){const tokens=q.toLowerCase().trim().split(/\s+/);return items.filter(e=>{const hay=[e.title,e.body,e.kind,e.status,spaces.find(s=>s.id===e.space)?.name,...Object.values(e.data),e.due?new Date(e.due).toLocaleDateString('en',{weekday:'long'}):''].join(' ').toLowerCase();return tokens.every(t=>hay.includes(t)||hay.split(/\W+/).some(w=>t.length>3&&distance(w,t)<=1));});}
function distance(a:string,b:string){if(Math.abs(a.length-b.length)>1)return 2;const d=Array.from({length:a.length+1},(_,i)=>[i,...Array(b.length).fill(0)]);for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length];}
export const moduleKinds:Record<string,{label:string;kind:Kind}[]>={ejj:[{label:'Leads',kind:'lead'},{label:'Websites',kind:'website'},{label:'Tasks',kind:'task'},{label:'Notes',kind:'note'},{label:'Ideas',kind:'idea'}],band:[{label:'Songs',kind:'song'},{label:'Rehearsals',kind:'rehearsal'},{label:'Practice',kind:'task'},{label:'Notes',kind:'note'},{label:'Ideas',kind:'idea'}],moshia:[{label:'Chapters',kind:'chapter'},{label:'Characters',kind:'character'},{label:'Plot threads',kind:'thread'},{label:'Locations',kind:'location'},{label:'Organizations',kind:'organization'},{label:'Timeline',kind:'event'},{label:'Research',kind:'note'},{label:'Ideas',kind:'idea'}],school:[{label:'Homework',kind:'assignment'},{label:'Tests',kind:'exam'},{label:'Subjects',kind:'subject'},{label:'Grades',kind:'grade'},{label:'Timetable',kind:'event'},{label:'Materials',kind:'note'}],personal:[{label:'Tasks',kind:'task'},{label:'Appointments',kind:'event'},{label:'Notes',kind:'note'},{label:'Ideas',kind:'idea'}]};
export const fields:Partial<Record<Kind,string[]>>={lead:['contact','email','phone','website','city','lastContact','nextAction','value','package'],website:['productionURL','repository','deploymentStatus','domain'],song:['artist','BPM','tuning','structure','chords','readiness'],rehearsal:['location','setlist','practiceTargets'],character:['aliases','age','relationships','affiliations','knowledge','secrets'],chapter:['POV','location','storyDate','characters','plotThreads','purpose','wordCount'],thread:['setup','development','payoff'],location:['description','relatedCharacters'],event:['location','characters','chapter','storyDate'],subject:['weighting','materials'],grade:['subject','grade','weight'],exam:['subject','studyTime'],assignment:['subject'],organization:['members','purpose']};
export function statuses(kind:Kind,space:string){if(space==='moshia')return ['POSSIBLE','PLANNED','CANON','REJECTED'];if(kind==='lead')return ['Lead','Contacted','Interested','Demo','Follow-up','Client','Lost'];if(kind==='song')return ['Learning','Rehearsing','Ready'];if(kind==='idea')return ['new','developing','promoted','archived'];return ['active','waiting','blocked','done'];}
export function validateEntity(v:unknown):v is Entity{if(!v||typeof v!=='object')return false;const e=v as Entity;return typeof e.id==='string'&&typeof e.title==='string'&&typeof e.body==='string'&&spaces.some(s=>s.id===e.space)&&Object.values(moduleKinds).flat().some(k=>k.kind===e.kind)&&typeof e.status==='string'&&!Number.isNaN(Date.parse(e.created))&&!Number.isNaN(Date.parse(e.updated))&&!!e.data&&typeof e.data==='object'&&Object.values(e.data).every(x=>typeof x==='string')&&(!e.due||!Number.isNaN(Date.parse(e.due)));}
