import {useEffect,useRef,useState} from 'react';
import {Plus} from 'lucide-react';
import {Modal} from './components';
import {makeEntity,statuses,type Entity} from './core';
import {creationSpec,fieldLabel} from './creation';
import {spaceOf} from './primitives';
import * as db from './db';
export function CreateSheet({initial,close,save}:{initial:Partial<Entity>;close:()=>void;save:(e:Entity)=>Promise<void>}){
 const [draft,setDraft]=useState(()=>makeEntity({...initial,status:initial.status||statuses(initial.kind!,initial.space||'personal')[0]})),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[canon,setCanon]=useState(false);const savingRef=useRef(false),latest=useRef(draft);latest.current=draft;
 const spec=creationSpec(draft.space,draft.kind);const space=spaceOf(draft.space);
 useEffect(()=>{let live=true;db.creationDraft(draft.space,draft.kind).then(saved=>{if(live){if(saved&&!initial.title)setDraft(saved);setReady(true)}}).catch(()=>{if(live){setError('Your saved draft couldn’t be opened.');setReady(true)}});return()=>{live=false;if(!savingRef.current)db.saveCreationDraft(latest.current.space,latest.current.kind,latest.current).catch(()=>{})}},[]);
 useEffect(()=>{if(!ready||saving)return;const timer=setTimeout(()=>db.saveCreationDraft(draft.space,draft.kind,draft).catch(()=>setError('Your draft couldn’t be kept. Leave this sheet open until you save.')),250);return()=>clearTimeout(timer)},[draft,ready,saving]);
 const patch=(update:Partial<Entity>)=>setDraft(current=>({...current,...update}));
 async function closeDraft(){try{await db.saveCreationDraft(draft.space,draft.kind,draft);close()}catch{setError('Your draft couldn’t be kept. Leave this sheet open until you save.')}}
 async function commit(approved=false){if(!draft.title.trim()||saving||!ready)return;if(draft.space==='moshia'&&draft.status==='CANON'&&!approved){setCanon(true);return}setSaving(true);savingRef.current=true;try{await save({...draft,title:draft.title.trim()});await db.saveCreationDraft(draft.space,draft.kind,null)}catch{savingRef.current=false;setError('This item couldn’t be saved. Your details are still here.')}finally{setSaving(false)}}
 const detail=(key:string)=><label className="field" key={key}>{fieldLabel(key)}<textarea aria-label={fieldLabel(key)} rows={key==='setup'||key==='development'||key==='payoff'||key==='purpose'?2:1} value={draft.data[key]||''} onChange={e=>patch({data:{...draft.data,[key]:e.target.value}})}/></label>;
 return <Modal title={spec.title} close={closeDraft}><form className={'creation-form creation-'+draft.kind} style={{'--creation-accent':space.color} as React.CSSProperties} onSubmit={e=>{e.preventDefault();commit()}}>
 <div className="creation-context"><span>{space.name}</span><p>{spec.hint}</p></div>
 <div className="creation-writing"><label className="field">{spec.titleLabel}<input autoFocus value={draft.title} onChange={e=>patch({title:e.target.value})} disabled={!ready} autoComplete="off"/></label><label className="field">{spec.bodyLabel}<textarea aria-label={spec.bodyLabel} rows={2} value={draft.body} onChange={e=>patch({body:e.target.value})}/></label></div>
 {spec.details.length>0&&<section className="creation-details"><h3>{spec.section}</h3><div className="creation-fields">{spec.details.slice(0,3).map(detail)}</div>{spec.details.length>3&&<details><summary>More details</summary><div className="creation-fields">{spec.details.slice(3).map(detail)}</div></details>}</section>}
 <div className="creation-state"><label className="field">{draft.space==='moshia'?'Story state':'State'}<select aria-label={draft.space==='moshia'?'Story state':'State'} value={draft.status} onChange={e=>{patch({status:e.target.value});setCanon(false)}}>{statuses(draft.kind,draft.space).map(state=><option key={state}>{state}</option>)}</select></label>{draft.space==='moshia'&&<p className="help muted">Possibilities stay possibilities. Canon is always your choice.</p>}
 {['task','lead','assignment','exam','event','rehearsal'].includes(draft.kind)&&<details><summary>Add a date</summary><label className="field">When<input type="datetime-local" value={draft.due?new Date(new Date(draft.due).getTime()-new Date(draft.due).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>patch({due:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label></details>}</div>
 {error&&<p role="alert" className="help">{error}</p>}{canon?<div className="canon-confirm"><strong>Add this to canon?</strong><p>This marks the material as established in Moshia.</p><button type="button" className="primary" onClick={()=>commit(true)}>Add to canon</button><button type="button" className="quiet" onClick={()=>setCanon(false)}>Keep editing</button></div>:<div className="modal-actions"><span className="help muted">Draft kept on this device</span><button className="primary" type="submit" disabled={!ready||!draft.title.trim()||saving}><Plus size={17}/>{saving?'Saving…':spec.title}</button></div>}
 </form></Modal>
}
