import {openDB} from 'idb';
import {defaults, type Entity,type Settings,type Activity,validateEntity,makeEntity,parseCapture} from './core';
const db=openDB('ediz-os',1,{upgrade(db){db.createObjectStore('entities',{keyPath:'id'});db.createObjectStore('settings');db.createObjectStore('activity',{keyPath:'id'});db.createObjectStore('attachments',{keyPath:'id'});db.createObjectStore('snapshots',{keyPath:'id'});}});
export async function load(){const d=await db;return {items:await d.getAll('entities') as Entity[],settings:({...defaults,...await d.get('settings','profile')}) as Settings,activity:await d.getAll('activity') as Activity[]};}
export async function save(e:Entity,action='Updated'){const d=await db;const tx=d.transaction(['entities','activity'],'readwrite');await tx.objectStore('entities').put(e);await tx.objectStore('activity').put({id:crypto.randomUUID(),entityId:e.id,title:e.title,action,at:new Date().toISOString()});await tx.done;}
export async function remove(id:string){const d=await db;await d.delete('entities',id);}
export async function saveSettings(s:Settings){await (await db).put('settings',s,'profile');}
export async function addFile(entityId:string,file:File){await (await db).put('attachments',{id:crypto.randomUUID(),entityId,name:file.name,type:file.type,bytes:await file.arrayBuffer(),at:new Date().toISOString()});}
export async function files(entityId:string){return (await (await db).getAll('attachments')).filter(f=>f.entityId===entityId).map(f=>({...f,blob:f.blob||new Blob([f.bytes],{type:f.type})})) as {id:string;name:string;type:string;blob:Blob}[];}
export async function backup(){const state=await load();const attachments=await (await db).getAll('attachments');const encoded=await Promise.all(attachments.map(async f=>({...f,blob:undefined,bytes:undefined,base64:await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result as string);r.onerror=()=>reject(r.error);r.readAsDataURL(f.blob||new Blob([f.bytes],{type:f.type}));})})));return {format:'ediz-os',version:1,exported:new Date().toISOString(),...state,attachments:encoded};}
export async function snapshot(force=false){const d=await db;const id=force?new Date().toISOString():new Date().toISOString().slice(0,10);if(!force&&await d.get('snapshots',id))return;const state=await load();await d.put('snapshots',{id,...state});const all=await d.getAllKeys('snapshots');for(const k of all.sort().slice(0,-7))await d.delete('snapshots',k);}
export function download(name:string,data:unknown){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:typeof data==='string'?'text/plain':'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function parseImport(text:string,filename:string,space='personal'):Entity[]{if(/\.json$/i.test(filename)){const json=JSON.parse(text);const list=Array.isArray(json)?json:json.items;if(!Array.isArray(list)||!list.every(validateEntity))throw new Error('This JSON does not contain valid Ediz OS records.');return list;}if(/\.ics$/i.test(filename)){return text.split('BEGIN:VEVENT').slice(1).map(block=>{const value=(key:string)=>block.match(new RegExp('^'+key+'(?:;[^:]*)?:(.*)$','m'))?.[1]?.trim();const raw=value('DTSTART');let due:string|undefined;if(raw){const m=raw.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})(Z)?)?/);if(m)due=new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]||'12'}:${m[5]||'00'}:${m[6]||'00'}${m[7]||''}`).toISOString();}return makeEntity({space,kind:'event',title:value('SUMMARY')||'Calendar event',body:value('DESCRIPTION')||'',due,data:{location:value('LOCATION')||''}});});}if(/\.csv$/i.test(filename)){const rows=csv(text);const headers=rows.shift()?.map(h=>h.toLowerCase().trim())||[];return rows.filter(r=>r.some(Boolean)).map(row=>{const record=Object.fromEntries(headers.map((h,i)=>[h,row[i]||'']));const title=record.title||record.content||record.business||record.name||row[0];const kind=record.business?'lead':'task';return makeEntity({space,kind,title,body:record.description||record.notes||'',status:kind==='lead'?'Lead':'active',due:record.due&&!Number.isNaN(Date.parse(record.due))?new Date(record.due).toISOString():undefined,data:record});});}return text.split(/\n(?=#+\s)|\n\s*\n/).filter(x=>x.trim()).map(block=>makeEntity({...parseCapture(block.replace(/^#+\s*/,'')),space,kind:'note'}));}
export function csv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
export async function importItems(items:Entity[]){const d=await db;const existing=await d.getAll('entities') as Entity[];const keys=new Set(existing.map(e=>`${e.space}:${e.kind}:${e.title.toLowerCase().trim()}`));let count=0;const tx=d.transaction('entities','readwrite');for(const e of items){const key=`${e.space}:${e.kind}:${e.title.toLowerCase().trim()}`;if(!keys.has(key)){await tx.store.put(e);keys.add(key);count++;}}await tx.done;return count;}
export async function restoreAttachments(raw:unknown){if(!Array.isArray(raw))return;const d=await db;for(const f of raw){if(typeof f.id==='string'&&typeof f.entityId==='string'&&typeof f.base64==='string'&&f.base64.startsWith('data:')){const blob=await (await fetch(f.base64)).blob();await d.put('attachments',{id:f.id,entityId:f.entityId,name:String(f.name),type:String(f.type),bytes:await blob.arrayBuffer()});}}}
export async function restoreBackup(raw:unknown){const b=raw as {format:string;version:number;items:Entity[];activity:Activity[];settings:Settings;attachments:{id:string;entityId:string;name:string;type:string;base64:string}[]};if(b?.format!=='ediz-os'||b.version!==1||!Array.isArray(b.items)||!b.items.every(validateEntity))throw new Error('This is not a valid Ediz OS backup.');const attachments=await Promise.all((b.attachments||[]).map(async f=>{if(typeof f.id!=='string'||typeof f.entityId!=='string'||typeof f.base64!=='string'||!f.base64.startsWith('data:'))throw new Error('An attachment in this backup is invalid.');return {id:f.id,entityId:f.entityId,name:String(f.name),type:String(f.type),bytes:await (await fetch(f.base64)).arrayBuffer()};}));const d=await db;const tx=d.transaction(['entities','settings','activity','attachments'],'readwrite');for(const name of ['entities','settings','activity','attachments'] as const)await tx.objectStore(name).clear();for(const e of b.items)await tx.objectStore('entities').put(e);for(const f of attachments)await tx.objectStore('attachments').put(f);for(const a of b.activity||[])if(typeof a.id==='string'&&typeof a.at==='string'&&typeof a.title==='string')await tx.objectStore('activity').put(a);await tx.objectStore('settings').put(cleanSettings(b.settings),'profile');await tx.done;}
export function cleanSettings(value:unknown):Settings {const s=(value||{}) as Partial<Settings>;return {...defaults,theme:['light','dark','system'].includes(s.theme||'')?s.theme!:defaults.theme,density:s.density==='compact'?'compact':'comfortable',focus:['all','ejj','school','band','moshia','personal'].includes(s.focus||'')?s.focus!:'all',labs:!!s.labs,localEndpoint:typeof s.localEndpoint==='string'?s.localEndpoint:undefined,lastBackup:typeof s.lastBackup==='string'?s.lastBackup:undefined,recentId:typeof s.recentId==='string'?s.recentId:undefined};}
export async function snapshots(){return (await (await db).getAll('snapshots')).sort((a,b)=>b.id.localeCompare(a.id)) as {id:string;items:Entity[];settings:Settings;activity:Activity[]}[];}
export async function restoreSnapshot(id:string){const d=await db;const s=await d.get('snapshots',id);if(!s)throw new Error('This snapshot is unavailable.');const tx=d.transaction(['entities','activity'],'readwrite');await tx.objectStore('entities').clear();await tx.objectStore('activity').clear();for(const e of s.items)await tx.objectStore('entities').put(e);for(const a of s.activity)await tx.objectStore('activity').put(a);await tx.done;}

export type CaptureDraft={text:string;space:string;kind:string;due:string};
export async function captureDraft(){return (await (await db).get('settings','captureDraft')) as CaptureDraft|undefined;}
export async function saveCaptureDraft(draft:CaptureDraft|null){const d=await db;if(draft)await d.put('settings',draft,'captureDraft');else await d.delete('settings','captureDraft');}

// Typed creation never overwrites the spontaneous quick-capture draft.
export async function creationDraft(space:string,kind:string){return await (await db).get('settings',`creation:${space}:${kind}`) as Entity|undefined;}
export async function saveCreationDraft(space:string,kind:string,draft:Entity|null){const database=await db;const key=`creation:${space}:${kind}`;if(draft)await database.put('settings',draft,key);else await database.delete('settings',key);}
