import {meaningfulUpdates} from './surfaces';
import {useState} from 'react';
import {ArrowRight,ChevronRight,Music,Clock} from 'lucide-react';
import {spaces,type Entity} from './core';
import {dateLabel} from './primitives';
export function StoryTimeline({items,open}:{items:Entity[];open:(e:Entity)=>void}){const [filter,setFilter]=useState('');const list=items.filter(e=>e.kind==='event'&&(!filter||[e.data.characters,e.data.location,e.data.chapter].join(' ').toLowerCase().includes(filter.toLowerCase()))).sort((a,b)=>(a.data.storyDate||a.due||a.created).localeCompare(b.data.storyDate||b.due||b.created));return <section><label className="search-input"><input aria-label="Filter story timeline" placeholder="Filter by character, chapter, or location…" value={filter} onChange={e=>setFilter(e.target.value)}/></label><div className="story-timeline">{list.map(e=><button key={e.id} onClick={()=>open(e)}><div className="timeline-date">{e.data.storyDate||dateLabel(e.due)}<span/></div><div><span className="status">{e.status}</span><h3>{e.title}</h3><p>{[e.data.chapter,e.data.location,e.data.characters].filter(Boolean).join(' · ')}</p></div><ChevronRight size={17}/></button>)}</div></section>}
export function SchoolWorkload({items}:{items:Entity[]}){const now=new Date();now.setHours(0,0,0,0);const days=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()+i);const list=items.filter(e=>['assignment','exam'].includes(e.kind)&&e.status!=='done'&&e.due&&new Date(e.due).toDateString()===d.toDateString());return {day:d,list,minutes:list.reduce((sum,e)=>sum+(e.duration||Number(e.data.studyTime)||0),0)};});if(!days.some(d=>d.list.length))return null;return <section className="workload"><div className="section-title"><h2>The week ahead</h2><span className="muted">School workload</span></div><div className="workload-days">{days.map(d=><div key={d.day.toISOString()} className={d.list.length?'has-work':''}><span>{d.day.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{d.list.length||'—'}</strong><small>{d.minutes?d.minutes+' min':d.list.length?'Estimate time':''}</small></div>)}</div><p>{days.filter(d=>d.minutes>=120).length?'Leave extra room on '+days.filter(d=>d.minutes>=120).map(d=>d.day.toLocaleDateString(undefined,{weekday:'long'})).join(' and ')+'.':'Add time estimates to see where the week needs more room.'}</p></section>}
export function LeadSummary({items}:{items:Entity[]}){const leads=items.filter(e=>e.kind==='lead');if(!leads.length)return null;const clients=leads.filter(e=>e.status==='Client');const value=clients.reduce((sum,e)=>sum+(Number(e.data.value)||0),0);return <div className="lead-summary"><div><strong>{leads.filter(e=>!['Client','Lost'].includes(e.status)).length}</strong><small>open relationships</small></div><div><strong>{leads.filter(e=>e.status==='Interested'||e.status==='Demo').length}</strong><small>interested / demo</small></div><div><strong>{clients.length}</strong><small>clients</small></div>{value>0&&<div><strong>{value.toLocaleString()}</strong><small>recorded client value</small></div>}</div>}
export function SongSetlist({songs,open}:{songs:Entity[];open:(e:Entity)=>void}){return <div className="song-list">{[...songs].sort((a,b)=>a.created.localeCompare(b.created)||a.id.localeCompare(b.id)).map((s,i)=><button key={s.id} onClick={()=>open(s)}><span className="song-number">{String(i+1).padStart(2,'0')}</span><div><strong>{s.title}</strong><small>{s.data.artist||'Original / unassigned artist'}</small></div><div className="song-details"><span>{s.data.BPM||'—'}<small>BPM</small></span><span>{s.data.tuning||'—'}<small>TUNING</small></span></div><span className="status">{s.status}</span><ChevronRight size={16}/></button>)}</div>}
export function ChapterIndex({chapters,open}:{chapters:Entity[];open:(e:Entity)=>void}){return <div className="chapter-index">{[...chapters].sort((a,b)=>a.created.localeCompare(b.created)||a.id.localeCompare(b.id)).map((e,i)=><button aria-label={'Open Chapter '+(i+1)+': '+e.title} key={e.id} onClick={()=>open(e)}><span className="chapter-number">{String(i+1).padStart(2,'0')}</span><div><div className="chapter-label"><strong>Chapter {i+1}</strong><span className="status">{e.status}</span></div><h3>{e.title}</h3><p>{[e.data.POV,e.data.location,e.data.wordCount?e.data.wordCount+' words':''].filter(Boolean).join(' · ')||'A chapter waiting for its context.'}</p>{e.data.purpose&&<small>{e.data.purpose}</small>}</div><ArrowRight size={18}/></button>)}</div>}
export function MeaningfulUpdates({items,onOpen,focus='all'}:{items:Entity[];onOpen:(e:Entity)=>void;focus?:string}){const imminent=meaningfulUpdates(items,focus);if(!imminent.length)return null;return <div className="meaningful-updates"><h2>Worth a look</h2>{imminent.slice(0,3).map(e=><button key={e.id} onClick={()=>onOpen(e)}><div><strong>{e.title}</strong><small>{e.kind==='website'?'A deployment needs attention.':e.kind==='exam'?'Coming up in the next two days.':'An open story thread has been quiet.'}</small></div><ChevronRight size={17}/></button>)}</div>}
