import {Plus,Upload,Calendar,Clock,SlidersHorizontal} from 'lucide-react';
import {type ReactNode} from 'react';
import {spaces,type Entity,type rank} from './core';
import {Mark,dateLabel,spaceOf} from './primitives';
import {MeaningfulUpdates} from './modules';
type Ranked=ReturnType<typeof rank>;
export function Today({priorities,items,upcoming,last,onCapture,onImport,onSpace,onReview,onOpen,onFocus,rows}:{greeting:string;priorities:Ranked;items:Entity[];upcoming:Entity[];last:Entity|null;onCapture:()=>void;onImport:()=>void;onSpace:(id:string)=>void;onReview:(period:'evening'|'weekly')=>void;onOpen:(e:Entity)=>void;onFocus:()=>void;rows:(list:Entity[],priorityRows?:boolean)=>ReactNode}){
const shortcuts=['Leads','Setlist','Chapters','Week','Capture'];
return <div className="today-page"><div className="page-heading today-heading"><span className="date">{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</span><h1 aria-label="Today">Today, Ediz<span className="heading-period">.</span></h1></div><div className="today-columns"><div className="today-primary"><section className="next-move"><div className="section-title"><h2>Your next move</h2>{priorities.length>0&&<button className="icon-button glass-control" aria-label="Change focus" onClick={onFocus}><SlidersHorizontal size={18}/></button>}</div>{priorities.length?<><div className="grouped-list">{rows(priorities.slice(0,4).map(p=>p.entity),true)}</div><p className="daily-context">{priorities[0].reasons[0]}</p>{priorities.length>4&&<details className="other-priorities"><summary>{priorities.length-4} other next steps</summary>{rows(priorities.slice(4).map(p=>p.entity))}</details>}</>:<div className="quiet-morning"><h3>Nothing pressing.</h3><p>Capture a thought or bring in your existing work.</p></div>}<div className="next-actions"><button className="quiet" aria-label="Capture something" onClick={onCapture}><Plus size={18}/> Capture</button><button className="quiet" onClick={onImport}><Upload size={17}/> Import</button></div></section>
<section className="today-spaces"><div className="section-title"><h2>Your spaces</h2></div><div className="space-list">{spaces.map((s,i)=><div key={s.id} className="space-shortcut"><button className="space-shortcut-main" onClick={()=>onSpace(s.id)}><Mark space={s.id}/><span><strong>{s.name}</strong><small>{s.description}</small></span></button><button className="quiet space-quick" onClick={()=>i===4?onCapture():onSpace(s.id)} aria-label={shortcuts[i]+' · '+s.name}>{shortcuts[i]}</button></div>)}</div></section></div><div className="today-secondary">{last&&<section className="continue-section"><div className="section-title"><h2>Continue where you left off</h2></div><button className="continue-panel" onClick={()=>onOpen(last)}><Mark space={last.space}/><div><h3>{last.title}</h3><p>{spaceOf(last.space).name}</p></div></button></section>}{upcoming.length>0&&<section className="schedule"><div className="section-title"><h2>Coming up</h2></div><div className="agenda grouped-list">{upcoming.map(e=><button key={e.id} onClick={()=>onOpen(e)}><span>{dateLabel(e.due)}<small>{new Date(e.due!).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></span><div><strong>{e.title}</strong><small>{spaceOf(e.space).name}</small></div></button>)}</div></section>}<div className="review-controls"><button onClick={()=>onReview('evening')}><Calendar size={18}/><span>Review today</span></button><button onClick={()=>onReview('weekly')} aria-label="Review this week"><Clock size={18}/></button></div><MeaningfulUpdates items={items} onOpen={onOpen}/></div></div></div>}
