import {Plus,Upload,Calendar,Clock,SlidersHorizontal} from 'lucide-react';
import {type ReactNode} from 'react';
import {spaces,type Entity,type rank} from './core';
import {Mark,dateLabel,spaceOf} from './primitives';
import {orderedSpaces} from './surfaces';
import {MeaningfulUpdates} from './modules';
type Ranked=ReturnType<typeof rank>;
export function Today({greeting,priorities,items,upcoming,last,onCapture,onImport,onSpace,onReview,onOpen,onFocus,focus,onShortcut,rows}:{greeting:string;priorities:Ranked;items:Entity[];upcoming:Entity[];last:Entity|null;onCapture:()=>void;onImport:()=>void;onSpace:(id:string)=>void;onReview:(period:'evening'|'weekly')=>void;onOpen:(e:Entity)=>void;onFocus:()=>void;focus:string;onShortcut:(id:string)=>void;rows:(list:Entity[],priorityRows?:boolean)=>ReactNode}){
const shortcuts:Record<string,string>={ejj:'Leads',band:'Setlist',moshia:'Chapters',school:'Homework',personal:'Capture'};
return <div className="today-page"><div className="page-heading today-heading"><div><p className="today-greeting">{greeting}, Ediz.</p><h1 aria-label="Today">Today<span className="heading-period">.</span></h1></div><time className="today-date-pebble" dateTime={new Date().toLocaleDateString('en-CA')}><span>{new Date().toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{new Date().getDate()}</strong><small>{new Date().toLocaleDateString(undefined,{month:'short'})}</small></time></div><div className="today-focus-bar"><button className="today-focus" onClick={onFocus} aria-label={focus==='all'?'Choose workspace focus':'Focused on '+spaceOf(focus).name}><span style={{background:focus==='all'?'var(--muted)':spaceOf(focus).color}}/>{focus==='all'?'Balanced day':spaceOf(focus).name}<SlidersHorizontal size={15}/></button><span>{priorities.length?`${Math.min(4,priorities.length)} next steps`:'Room to choose'}</span></div><div className="today-columns"><div className="today-primary"><section className="next-move"><div className="section-title"><h2>What matters</h2>{<button className="icon-button glass-control" aria-label="Change focus" onClick={onFocus}><SlidersHorizontal size={18}/></button>}</div>{priorities.length?<><div className="grouped-list">{rows(priorities.slice(0,4).map(p=>p.entity),true)}</div><details className="priority-reasons"><summary>Why these next steps?</summary>{priorities.slice(0,4).map(p=><div key={p.entity.id}><strong>{p.entity.title}</strong><p>{p.reasons.join(' ')}</p></div>)}</details>{priorities.length>4&&<details className="other-priorities"><summary>{priorities.length-4} other next steps</summary>{rows(priorities.slice(4).map(p=>p.entity))}</details>}</>:<div className="quiet-morning"><h3>Nothing pressing.</h3><p>Bring in your work. The important things will surface here.</p></div>}<div className="next-actions"><button className="quiet" aria-label="Capture something" onClick={onCapture}><Plus size={18}/> Capture</button><button className="quiet" onClick={onImport}><Upload size={17}/> Import</button></div></section>
{last&&<section className="continue-section"><div className="section-title"><h2>Continue</h2></div><button className="continue-panel" onClick={()=>onOpen(last)}><Mark space={last.space}/><div><h3>{last.title}</h3><p>{spaceOf(last.space).name}</p></div></button></section>}{upcoming.length>0&&<section className="schedule"><div className="section-title"><h2>Coming up</h2></div><div className="agenda grouped-list">{upcoming.map(e=><button key={e.id} onClick={()=>onOpen(e)}><span>{dateLabel(e.due)}<small>{new Date(e.due!).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></span><div><strong>{e.title}</strong><small>{spaceOf(e.space).name}</small></div></button>)}</div></section>}<MeaningfulUpdates items={items} onOpen={onOpen} focus={focus}/></div><div className="today-secondary"><section className="today-spaces"><div className="section-title"><h2>Your spaces</h2></div><div className="space-list">{orderedSpaces(focus).map(s=><div key={s.id} className="space-shortcut"><button className="space-shortcut-main" onClick={()=>onSpace(s.id)}><Mark space={s.id}/><span><strong>{s.name}</strong><small>{s.description}</small></span></button><button className="quiet space-quick" onClick={()=>s.id==='personal'?onCapture():onShortcut(s.id)} aria-label={shortcuts[s.id]+' · '+s.name}>{shortcuts[s.id]}</button></div>)}</div></section><div className="review-controls"><button onClick={()=>onReview('evening')}><Calendar size={18}/><span>Review today</span></button><button onClick={()=>onReview('weekly')} aria-label="Review this week"><Clock size={18}/><span>This week</span></button></div></div></div></div>}
